// Do not edit this file, instead go into ./generic.js or ./specific-*.spec.js

import genericSpecs from './generic'

describe('Angular',{baseUrl:'http://localhost:6008/'}, ()=>{
    genericSpecs();
})

