// Do not edit this file, instead go into ./generic.js or ./specific-*.spec.js

import genericSpecs from './generic'

describe('React',{baseUrl:'http://localhost:6011/'},  ()=>{
    genericSpecs();
})

