// Do not edit this file, instead go into ./generic.js or ./specific-*.spec.js

import genericSpecs from './generic'

describe('Vanilla',{baseUrl:'http://localhost:6010/'},  ()=>{
    genericSpecs();
})

