// Do not edit this file, instead go into ./generic.js or ./specific-*.spec.js

import genericSpecs from './generic'

describe('Vue',{baseUrl:'http://localhost:6009/'},  ()=>{
    describe('Without HyperFormula', ()=>{
        genericSpecs();
    })
    describe('With HyperFormula', ()=>{
        genericSpecs('Hf');
    })
})

