// Do not edit this file, instead go into ./generic.js or ./specific-*.spec.js

import genericSpecs from './generic'

describe('Vue',{baseUrl:'http://localhost:6009/'},  ()=>{
    genericSpecs();
})

